import './globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    // Some Extentions couse an error an this is why we need to suppress the warning.
    <html suppressHydrationWarning={true} lang="en">
      <body suppressHydrationWarning={true}>{children}</body>
    </html>
  )
}
